# Generated by Django 4.2.13 on 2024-06-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_usuario_adaptabilidad_usuario_aprendizaje_logico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='empatia',
            field=models.IntegerField(default=0),
        ),
    ]
